### ISSUE TITLE
Suggestion: Volunteering

### ISSUE THREAD

**Issue by ghost** [getgrav/grav-skeleton-resume-site#1]
Hey there,

Could definitely place this in experience. But maybe a dedicated section to volunteering would be nice. 

Best regards,

Coen

**Comment by hexplor** [comment]
Well.. You can easily create your own section. Just look for an examples and add your own page with desired layout.

**Comment by ghost** [comment]
That is a rapid response! 

I thought so as well, which I tried by copying a folder from either left or right and renaming it. However it didn't show up on the webpage. I'm sure I do something wrong, but I couldn't figure it out. I also tried this through the admin panel you can install with grav.

Do you have any further suggestion?

**Comment by ghost** [comment]
Ah I missed adding the .html.twig file in the template/layouts. Sorry!

**Comment by hexplor** [comment]
BTW. I don't think you even need to duplicate template layouts. All you have to do:
1) go to your "pages" dir
2) go to left or right sidebar
3) duplicate folder named "education" and call it volunteer
4) Edit content of education.md (don't change it's name education.md means it will look for education.html.twig template)

Inside .md page you will notice that you can change everything from title to content :)

P.S. Good for you that you're doing volunteer work. I'm doing it a lot myself :)
