### ISSUE TITLE
Templates not available

### ISSUE THREAD

**Issue by Jcambass** [getgrav/grav-skeleton-resume-site#7]
Is it possible that this skeleton is not compatible with the latest grav version? Everything works fine until I edit something inside the education or any other sections. After editing and saving the page the template falls back to 'default'. The selectable Templates only includes a 'Resume' which trows an error upon calling the site.

**Comment by flaviocopes** [comment]
The Resume theme defines only the `resume` page template: https://github.com/getgrav/grav-theme-resume/tree/develop/templates (in addition to `default`).

Which error does it give you? Screenshot?

**Comment by Jcambass** [comment]
After changing and saving the content (text) of a page (I tried language skills and eduction) the section is not shown on the page anymore. The only change that was visible to me was the change of the template to default?

I'm quit knew to grav.. I'll try reproducing it later this week.

**Comment by Giaggio** [comment]
Hi. Say problem for me. The sections stay empty (excluding title, i.e. EDUCATION) after I edit them.  I would only show the content typed in the Admin panel.
